version: "3"

services:
  node:
    container_name: nodeAPI
    image: node:latest
#    env_file:
#      - .env.development
    ports:
      - "4000:4000"
    expose:
      - 4000
    working_dir: /home/node/app
    volumes:
      - ./node-api:/home/node/app
    command: bash -c "npm install && npm run dev"
  database:
    container_name: db
    image: mysql
    ports:
    - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dimipak"
      MYSQL_USER: "mydimi"
      MYSQL_PASSWORD: "mypass"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/nodeAPI.conf:/etc/nginx/conf.d/default.conf
      - ./services/ssl:/etc/ssl/certs/dimipak
    links:
      - node