version: "3"

services:
  node:
    container_name: nodeAPI
    image: node:latest
    network_mode: host
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    expose:
      - 4000
    working_dir: /home/node/app
    volumes:
      - ./src/node-api:/home/node/app
      - ./services/node/openssl.cnf:/etc/ssl/openssl.cnf
    command: bash -c "npm install && npm run dev"
  database:
    container_name: db
    network_mode: host
    image: mysql
    ports:
    - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dimipak"
      MYSQL_USER: "mydimi"
      MYSQL_PASSWORD: "mypass"
  nginx:
    container_name: nginx
    image: nginx:latest
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/nodeAPI.conf:/etc/nginx/conf.d/default.conf
      - ./keys/ssl:/etc/ssl/certs/dimipak

  frontend:
    container_name: vue
    image: node:latest
    network_mode: host
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
      - NODE_ENV=development
    working_dir: /home/node/app
    expose:
      - 8080
    volumes:
      - ./src/frontend:/home/node/app
    ports:
      - "8080:8080"
    command: bash -c "npm install -g @vue/cli && npm install && npm run serve"
  go:
    container_name: goAPI
    image: golang:latest
    working_dir: /go/src/app
    network_mode: host
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./src/go-api:/go/src/app
    command: go run main.go